---
title: "DS 301 Project"
author: "Patrick Wenzel"
date: "4/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
options(dplyr.tibble.inform = FALSE)
options(scipen = 6)
library(tidyr)
library(dplyr)
library(ISLR)
library(kableExtra)
library(car)
library(leaps)
library(caret)
library(glmnet)
library(ROCR)
library(datasets)
library(tree)
library(class)
library(MASS)
library(RColorBrewer)
```

```{r, echo = T}
counted2015 <- read.csv("./thecounted-data/the-counted-2015.csv", header = TRUE)
counted2016 <- read.csv("./thecounted-data/the-counted-2016.csv", header = TRUE)
df <- rbind(counted2015, counted2016)
```

```{r}
head(counted2015, 5)
head(counted2016, 5)
str(counted2015)
str(counted2016)
dim(counted2015)
dim(counted2016)

df$raceethnicity <- as.factor(df$raceethnicity)
df$state <- as.factor(df$state)
df$classification <- as.factor(df$classification)
df$armed <- as.factor(df$armed)
df$date <- as.Date(paste(match(df$month, month.name), "/", df$day, "/", df$year, sep=""), format = "%m/%d/%Y")

str(df)
```

```{r, echo = T}
reGroup <- df %>% group_by(raceethnicity) %>%
                    summarise(num_people = n())

ggplot(reGroup, aes(x = raceethnicity, y = num_people, color = raceethnicity, fill = raceethnicity)) + geom_bar(stat="identity") + ggtitle("Number of People Killed per Race/Ethnicity") + xlab("Race/Ethnicity") + ylab("Number of People") + theme(axis.text.x = element_text(angle = 90))
```

```{r, echo = T}
byMonth <- df %>% group_by(month) %>%
                  summarise(numDeaths = n())
byMonth <- byMonth[order(match(byMonth$month, month.name)), ]
byMonth$month <- factor(byMonth$month, levels = month.name)

ggplot(byMonth, aes(x = month, y = numDeaths, group = 1)) + geom_line() + theme(axis.text.x = element_text(angle = 90))
```

```{r, echo = T}
armedGroup <- df %>% group_by(armed) %>%
                        summarise(numPeople = n())
ggplot(armedGroup, aes(x = armed, y = numPeople, color = armed, fill = armed)) + geom_bar(stat="identity") + ggtitle("Number of People Killed per Armed Classification") + xlab("Armed Classification") + ylab("Number of People") + theme(axis.text.x = element_text(angle = 90))
```

```{r, echo = T}
classGroup <- df %>% group_by(classification) %>%
                      summarise(numPeople = n())
classGroup
```

```{r, echo = T}
ageGroup <- df[df$age != "Unknown",]
ageGroup$age[which(ageGroup$age == "40s")] <- "40"
ageGroup$age <- strtoi(ageGroup$age)
ggplot() + geom_histogram(data = ageGroup, aes(x=age), color = "black", fill = "blue", binwidth = 5)
```

```{r}
df$state[which(df$state == "DC")] <- "VA"
df$State <- tolower(state.name[match(df$state, state.abb)])
df2 <- df
states <- map_data('state')
stateGroup <- df %>% group_by(State) %>%
                        summarise(numPeople = n())
stateGroup <- full_join(states, stateGroup, by = c('region' = 'State'))

ggplot(stateGroup, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill=numPeople)) + 
  geom_path() + 
  scale_fill_gradientn(colours=colorRampPalette(brewer.pal(11, "Reds"))(100), na.value="grey90") + 
  coord_map() + 
  ggtitle('Predicted Voted Political Party by State') + xlab('') + ylab('') + labs(fill = 'Predicted State Winner') + 
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())             
```

```{r, echo = T}
stateGroup2 <- df2 %>% group_by(State) %>%
                        summarise(numPeople = n())
stateGroup2$numPeople[stateGroup2$State %in% c("california", "texas", "florida")] <- 0
stateGroup2 <- full_join(states, stateGroup2, by = c('region' = 'State'))

ggplot(stateGroup2, aes(x = long, y = lat, group = group)) + 
  geom_polygon(aes(fill=numPeople)) + 
  geom_path() + 
  scale_fill_gradientn(colours=colorRampPalette(brewer.pal(9, "Reds"))(100), na.value="grey90") + 
  coord_map() + 
  ggtitle('Predicted Voted Political Party by State') + xlab('') + ylab('') + labs(fill = 'Predicted State Winner') + 
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) 
```


















